name: end_to_end
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
env:
  PROJECT_NAME: "ZeroOps Production"
jobs:
  set_up_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          python3 -m pytest
          echo "all success ready for $PROJECT_NAME"
