name: set_up_env
on: push
env:
  API_KET: ${{ secrets.API_KEY }}
jobs:
    set_up_env:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: echo "Key length ${#API_KEY}"
