name: set_up_env
on: push
jobs:
    set_up_env:
      runs-on: ubuntu-latest
      env:
        API_KET: ${{ secrets.API_KET }}
      steps:
        - uses: actions/checkout@v4
        - run: echo "Key length ${#API_KET}"
