name: set up env
on: push
env:
  API_KEY: ${{ secrets.API_KET }}
jobs:
  set_up_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Key length: ${#API_KET}"
